apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-depl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: teamsservice
  template:
    metadata:
      labels:
        app: teamsservice
    spec:
      containers:
        - name: teamsservice
          image: gerhardt0011/teamsservice:latest
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: teams-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: teamsservice
  ports:
    - name: teamsservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: teamsgrpc
      protocol: TCP
      port: 8080
      targetPort: 8080
