apiVersion: v1
kind: PersistentVolume
metadata:
    name: customers-mongo-data-pv
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 5Gi
    hostPath:
        path: /data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: customers-mongo-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi